INSERT INTO RECORDINGS (title, duration, status, sedation, activation)
VALUES
('MRI Brain Scan', 1800, 'SCHEDULED', 'Mild Sedation', 'Standard Neural Activity'),
('CT Chest Scan', 2400, 'SCHEDULED', 'No Sedation Required', 'Normal Organ Function'),
('X-Ray Arm', 300, 'SCHEDULED', 'No Sedation Required', 'Not Applicable'),
('Ultrasound Abdomen', 1200, 'SCHEDULED', 'No Sedation Required', 'Normal Digestive Function'),
('EEG Monitoring', 3600, 'RECORDED', 'No Sedation Required', 'Brain Wave Patterns Recorded'),
('Heart Rate Test', 600, 'RECORDED', 'No Sedation Required', 'Cardiac Rhythm Monitored'),
('Stress Test', 1800, 'RECORDED', 'No Sedation Required', 'Increased Cardiovascular Response'),
('Endoscopy', 2700, 'RECORDED', 'Moderate Sedation', 'Gastrointestinal Reflexes Observed'),
('Sleep Study', 28800, 'RECORDED', 'No Sedation Required', 'Sleep Cycle Analysis'),
('Lung Function Test', 900, 'RECORDED', 'No Sedation Required', 'Pulmonary Function Measured'),
('MRI Full Body', 5400, 'REPORTED', 'Midazolam', 'High Activity'),
('CT Angiography', 4200, 'REPORTED', 'Propofol', 'Normal'),
('PET Scan', 7200, 'REPORTED', 'Ketamine', 'Increased Metabolism'),
('Echo Cardiogram', 1800, 'REPORTED', 'No Sedation Required', 'Stable Cardiovascular Function'),
('EEG with Stimulation', 3600, 'REPORTED', 'Thiopental', 'Seizure Activity Detected'),
('Blood Flow Analysis', 1200, 'REPORTED', 'No Sedation Required', 'Mild Hypoperfusion'),
('Neurophysiology Exam', 5400, 'REPORTED', 'Fentanyl', 'Elevated Neurological Responses'),
('Cerebral Blood Flow Test', 6000, 'REPORTED', 'Dexmedetomidine', 'Reduced Perfusion Detected'),
('Gastrointestinal Motility Test', 3600, 'REPORTED', 'Lorazepam', 'Normal Digestive Movement'),
('Cardiac Stress MRI', 4500, 'REPORTED', 'Etomidate', 'Cardiac Function Within Normal Limits');
